name: .NET

on:
  push:
    branches:
      - main
      - next
      - beta
      - dev
      - "*.x"
  pull_request:
    branches:
      - main
      - next
      - beta
      - dev
      - "*.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: Restore tools
        run: dotnet tool restore
      - name: Restore dependencies
        run: dotnet restore --locked-mode
      - name: Build
        run: dotnet build -c Debug --no-restore
      - name: Build container
        run: dotnet publish -c Debug --no-restore --os linux --arch x64 /t:PublishContainer -p ContainerRepository=azure-appinsights-emulator --getProperty:GeneratedContainerDigest src/hangy.Testcontainers.AzureApplicationInsights.Server/hangy.Testcontainers.AzureApplicationInsights.Server.csproj
      - name: Test
        run: dotnet test -c Debug --no-build -p:TestingPlatformCommandLineArguments="--report-trx --coverage --coverage-output-format cobertura --coverage-output coverage.cobertura.xml" -f net9.0
        env:
          APPINSIGHTS_IMAGE: azure-appinsights-emulator
      - name: Convert test results
        if: ${{ !cancelled() }}
        run: |
          find . -name "*.trx" -exec dotnet tool run trx2junit --output TestResults/JUnit {} +
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: hangy/Testcontainers.AzureApplicationInsights
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          files: TestResults/JUnit/*.xml
          token: ${{ secrets.CODECOV_TOKEN }}
